routes/web.php
<?php

use App\Http\Controllers\AuthenticationController;
use App\Http\Controllers\CommitteeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('home');

    Route::get('login', [AuthenticationController::class, 'showLogin'])->name('login');
    Route::post('login', [AuthenticationController::class, 'authenticate'])->name('login');
    Route::post('logout', [AuthenticationController::class, 'logout'])->name('logout');
    if (app()->environment('local')) {
        Route::get('login/as/{id}', [AuthenticationController::class, 'login_as'])->name('login_as');
    }

    // Committee routes
    Route::resource('committees', CommitteeController::class);

    // Event routes
    Route::resource('events', EventController::class);

    // Ticket routes
    Route::resource('tickets', TicketController::class);
    // TODO: add the other routes
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\Pivot;

class Event extends Pivot
{
    protected $table = 'events';

    protected $fillable = [
        'title',
        'description',
        'location',
        'start',
        'end',
        'committee_id',
        'capacity',
        'public',
    ];

    public function committee(): BelongsTo
    {
        return $this->belongsTo(Committee::class);
    }

    public function options(): HasMany
    {
        return $this->hasMany(EventOption::class, 'event_id');
    }

    public function fields(): HasMany
    {
        return $this->hasMany(EventField::class, 'event_id');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Models\Event;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        // $events = Event::where('created_at', '>=', now()->subDay())
        //            ->where('public', true)
        //            ->get();
        // TODO: Switch and check

        $events = Event::with('committee')->get();

        return view('events.index', compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Event $event)
    {
        return view('events.show', compact('event'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Event $event)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Event $event)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Event $event)
    {
        //
    }
}

resources/views/events/index.blade.php
@extends('layout.base')

@section('title', 'Events')

@section('main')

    <h1>Events</h1>

    <table class="table table-borderless table-striped">
        <thead>
            <tr>
                <th>Title</th> {{-- TODO: do we want to show this? --}}
                @if (auth()->check() && (auth()->user()->hasRole('admin') || auth()->user()->hasRole('board')))
                    <th>Committee Name</th>
                    <th>Status</th>
                @endif
                <th class="text-end">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($events as $item)
                <tr>
                    <td>
                        <a href="{{ route('events.show', $item->id) }}" class="btn event-title">{{ $item->title }}</a>
                    </td>
                    @if (auth()->check() && (auth()->user()->hasRole('admin') || auth()->user()->hasRole('board')))
                        <td>
                            <a href="#{{-- TODO: add route --}}" class="btn event-title">{{ $item->committee->name }}</a>
                        </td>
                        <td>
                            {{-- TODO: Add counts --}}
                            Checked In: {{ 0 }} <br>
                            Remaining: {{ 0 }}
                        </td>
                    @endif
                    <td>
                    @if (auth()->check() && (auth()->user()->hasRole('board') || auth()->user()->hasRole('admin')))
                        <a href="{{-- TODO: add route --}}" class="btn btn-secondary position-relative">
                            Show
                            tickets
                            <span class="badge text-bg-secondary bg-danger rounded-circle">
                                {{ 123}}
                                {{-- {{ $item->tickets->count() }} --}}
                                {{-- TODO: see line above --}}
                            </span>
                        </a>
                    @endif
                    @if (auth()->check() && (auth()->user()->hasRole('board') || auth()->user()->hasRole('admin')))
                        @can('update', $item)
                            <a href="{{ route('events.edit', $item->id) }}" class="btn btn-primary">
                                <i class="fas fa-edit"></i>
                            </a>
                        @endcan
                        <a href="{{ route('events.show', $item->id) }}" class="btn btn-primary position-relative">
                            Book Now
                        </a>
                    @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

@endsection

resources/views/events/show.blade.php
@extends('layout.base')

@section('title', $event->title)

@section('main')

    <h1>{{ $event->title }}</h1>
    <p>{{ $event->description }}</p>
    @isset($event->location)
        <p>The event will take place at {{ $event->location }}</p>
        <br>
    @endisset

    <p>Select your options for {{ $event->title }} </p>
    <br>
    {{-- TODO: change route to tickets.create --}}
    <form action="{{ route('home') }}" method="get">
        @csrf
        <input type="hidden" name="step" value="1">
        <input type="hidden" name="event_id" value="{{ $event->id }}">

        @include('tickets.options')

        <button type="submit" class="btn btn-primary">Next</button>
    </form>

@endsection