routes/web.php
<?php

use App\Http\Controllers\AuthenticationController;
use App\Http\Controllers\CommitteeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->group(function () {
    Route::get('/', function () {
        return view('welcome');
    })->name('home');

    Route::get('login', [AuthenticationController::class, 'showLogin'])->name('login');
    Route::post('login', [AuthenticationController::class, 'authenticate'])->name('login');
    Route::post('logout', [AuthenticationController::class, 'logout'])->name('logout');
    if (app()->environment('local')) {
        Route::get('login/as/{id}', [AuthenticationController::class, 'login_as'])->name('login_as');
    }

    // Committee routes
    Route::resource('committees', CommitteeController::class);

    // Event routes
    Route::resource('events', EventController::class);

    // Ticket routes
    Route::resource('tickets', TicketController::class);
    // TODO: add the other routes
});

resources/views/layout/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {{-- Title --}}
    <title>
        {{ config('app.name') }}
        @hasSection('title')
            - @yield('title')
        @endif
    </title>

    {{-- Styles and Scripts --}}
    @vite(['resources/sass/app.scss', 'resources/css/app.css', 'resources/js/app.js'])
    @yield('styles')

</head>
<body class="d-flex flex-column min-vh-100">

    @include('layout.topbar')

    @include('layout.navbar')

    <main>
        <div class="container my-5">
            @include('layout.error')
            @include('layout.success')
            @yield('main')
        </div>
    </main>

    @include('layout.footer')

    {{-- Scripts --}}
    {{-- TODO: Check if we need a better way of incorporating jquery --}}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    @yield('scripts')
</body>
</html>

resources/views/layout/error.blade.php
@if ($errors->any())
    <div class="alert alert-danger mb-3">
        The following errors occurred while processing your request:
        <ul class="mb-0">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layout/footer.blade.php
<footer class="mt-auto py-3 bg-dark">
    <div class="container">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-lg-3 col-md-6 mb-5">
                    <h4 class="title">Contact</h4>
                    <p>
                        VSV 'Leonardo da Vinci'<br>
                        Faculteit LR, TU Delft<br>
                        Kluyverweg 1<br>
                        2629 HS Delft<br>
                        015 27 85366<br>
                        <a href="mailto:vsv@tudelft.nl">vsv@tudelft.nl</a><br>
                        KVK 40397684<br>
                    </p>
                </div>
                <div class="col-lg-3 col-md-6 mb-5">
                    <h4 class="title"><a class="rsswidget" href="https://www.flightglobal.com/rss/news/"><img
                                class="rss-widget-icon" src="{{ asset('img/rss.png') }}" alt="RSS"></a>
                        <a href="#"> Aviation news</a>
                    </h4>
                </div>
                <div class="col-lg-3 col-md-6 mb-5">
                    <h4 class="title"><a class="rsswidget" href="https://www.flightglobal.com/rss/news/"><img
                                class="rss-widget-icon" src="{{ asset('img/rss.png') }}" alt="RSS"></a>
                        <a href="#"> Aviation news 2</a>
                    </h4>
                </div>
                <div class="col-lg-3 col-md-6 mb-5"></div>


                <div class="col-sm-12 copyright">
                    Copyright © 1945-2015 VSV 'Leonardo da Vinci'. All Rights Reserved.
                </div>


            </div>
        </div>
    </div>
    </div>
</footer>

resources/views/layout/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid">
        {{-- LOGO --}}
        <a class="navbar-brand" href="{{ route('home') }}">
            <img class="logo" src="{{ asset('img/logo_white.png') }}" alt="VSV Logo">
        </a> {{-- TODO: Change Href to correctly point to the home page --}}

        {{-- Hamburger Button (mobile/small screens) --}}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navigation"
            aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        {{-- Navigation items --}}
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        <i class="fas fa-users"></i>
                        Committees

                    </a> {{-- TODO: Add links --}}
                    <ul class="dropdown-menu submenu">
                        <li>
                            <a class="dropdown-item" href="{{ route('committees.index') }}">
                                Overview
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Add new
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        <i class="fas fa-ticket-alt"></i>
                        Events

                    </a> {{-- TODO: Add links --}}
                    <ul class="dropdown-menu submenu">
                        <li>
                            <a class="dropdown-item" href="{{ route('events.index') }}">
                                Overview
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Add new
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">
                        <i class="fas fa-users"></i>
                        Committees

                    </a> {{-- TODO: Add links --}}
                    <ul class="dropdown-menu submenu dropdown-menu-right">
                        <li>
                            <a class="dropdown-item" href="#">
                                Overview
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">
                                Add new
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/layout/success.blade.php
@if (session('success'))
    <div class="alert alert-success mb-3">
        {{ session('success') }}
    </div>
@endif

resources/views/layout/topbar.blade.php
<header>
    <div class="navbar-login py-0 header-top fixed-top">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 nav-login">

            @auth

            <li>
                <a class="register-btn" href="#"> Logged in as {{ Auth::user()->name }} </a>
            </li>
            <li>
                {{-- <a class="login-btn" href="{{ route('logout') }}">
                    Log out
                </a> --}}
                <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button class="login-btn" type="submit">
                        Logout
                    </button>
                </form>
            </li>

            @else

            <li>
                <a class="register-btn" href="#">
                    Not a member yet? Click here to register!
                </a>
            </li>
            <li>
                <a class="login-btn" href="{{ route('login', ['redirect' => url()->current()]) }}">
                    Login
                </a>
            </li>

            @endauth

        </ul>
    </div>
</header>